# Investiage other pairwise similarity 'measures' for HLA inter-similarity

Precompute all pairwise cosine similarities

```{r, warning=FALSE, echo=FALSE}
mass_spec_hlas <- file.path(ma_dir, 'presentation_score_validation', 'data') %>%
  list.files(pattern = 'Syste.*\\.csv', full.names = T) %>%
  plyr::llply(function(fn) {
    fh <- fread(fn)
    unique_patient_alleles <- fh[, unique(top_allele)] %>%
      setdiff('unclassified') %>%
      strsplit(';') %>%
      unlist %>% unique %>% sort %>% quickMHC::shortenHLA() %>%
      { setNames(., gsub('(.)\\d{4}', '\\1', .)) }
  }) %>% unlist %>% unique

all_pairwise_comps <- expand.grid(
  'allele1' = c(all_AB_hlas, all_C_hlas),
  # 'allele1' = focus_hlas,
  # 'allele2' = c(all_AB_hlas, all_C_hlas))
  'allele2' = mass_spec_hlas)
```

```{r, warning=FALSE, echo=FALSE}
source(file.path(ma_dir, 'immune_editing', 'HLA_presentation_scores_helpers.R'))

hla_sim_method <- 'trimmed_ols_coef'
hla_sim_method <- 'ols_coef_pr'
ncores <- 1
ncores <- 32
doParallel::stopImplicitCluster()
doParallel::registerDoParallel(cores = ncores)
par_opts <- list(.options.multicore = list(preschedule = FALSE))
redo <- T

plyr::l_ply(1:nrow(all_pairwise_comps), function(i) {
  alleles <- as.character(unlist(as.list(all_pairwise_comps[i, ])))
  message(glue('Processing {i}/{nrow(all_pairwise_comps)}'))

  compute_pairwise_corroboration(
    focus_allele = alleles[1], ancillary_allele = alleles[2],
    pr = 1.9, pr_ancillary = 1.9,
    redo = redo,
    # hla_sim_method = 'cosine',
    # hla_sim_method = 'scalar_projection',
    hla_sim_method = hla_sim_method,
    rds_sub_dir = file.path(rds_dir, 'focus_allele_avg_HLA_presentation'))
}, .parallel = parallel, .paropts = par_opts)
```
