```{r, load_brms_model, include=F, eval=F, warning=FALSE}
mod_id <- paste('FE', FE_vars, 'RE', RE_vars, collapse = '_', sep = '-')
mod_id <- 'limited_random_terms'
mod_fn <- file.path(rds_dir,
  glue::glue('rlm_NAYR_loss_complete_blm\\
    {make_flag(chains)}\\
    {make_flag(mod_id)}.rds'))

if (!file.exists(mod_fn)) {
  b_mod <- fit_meta_lm(f_setting_dtf, method = 'brem')
  saveRDS(b_mod, mod_fn)
} else {
  b_mod <- readRDS(mod_fn)
}
REs <- brms::ranef(b_mod)
FEs <- brms::fixef(b_mod)
```

```{r, warning=FALSE}
f_setting_dtf[, .N, c(grp_vars, 'tumor_type')]
f_setting_dtf[, .N, c(grp_vars)][order(N)][N > 25]
f_setting_dtf[, .N, c(grp_vars)][, hist(N, breaks = 28)]
```

Change one setting and check effect

```{r, warning=FALSE}
idx <- 14
args <- 
  f_setting_dtf[patient_inclusion_crit == 'TR'][idx] %>%
  pan_IE_res_to_call_args() %>%
  # modifyList(
  #   list(
  #     focus_allele = as.character(.$focus_allele),
  #     patient_inclusion_crit = as.character(.$patient_inclusion_crit),
  #     LOH_HLA = as.character(.$LOH_HLA),
  #     overlap_var = as.character(.$overlap_var),
  #     tumor_type = as.character(.$tumor_type)
  #   )
  # ) %>%
  { .[intersect(names(.), colnames(f_setting_dtf))] } %>%
  modifyList(list(tumor_type = NULL)) %>%
  { . }

args_alt <- args %>%
  modifyList(list(patient_inclusion_crit = 'strict_TR')) %>%
  { . }

setkeyv(f_setting_dtf, names(args))
as.list(f_setting_dtf[args])
as.list(f_setting_dtf[args_alt])
```

```{r, warning=FALSE}
REs <- brms::ranef(me_mod)
FEs <- brms::fixef(me_mod)
library(broom.mixed)
pacman::p_load(broom.mixed)

tidy(me_mod)
broom.mixed:::tidy.lme
tidy.mixed
print(tidy(me_mod,
    effects = c('fixed', 'ran_coefs'),
    conf.int = T), n = 5)
broom::glance.lmer(me_mod)
```


```{r, warning=FALSE}
library(Rfast)

# X <- f_setting_dtf %>%
#   dplyr::select(one_of(grp_vars)) %>%
#   # lapply(class)
#   # lapply(as.integer) %>%
#   bind_cols() %>%
#   # as.matrix
#   { . }

c_formula <-
  as.formula(sprintf('yr_fractional_change ~ (%s)',
      paste(grp_vars, collapse = ' + ')))
X <- model.matrix(c_formula, data = f_setting_dtf)
Y <- f_setting_dtf %>% pull(yr_fractional_change)
id <- f_setting_dtf %>% pull(project_extended) %>% as.integer
# id <- f_setting_dtf %>% pull(project_extended)
mod <- suppressWarnings(
  rint.reg(y = Y, x = X, id = id, tol = 1e-8,
    ranef = T, maxiters = 1000)
)
print(mod)
```

```{r, warning=FALSE}
source(file.path('~/antigenic_space', 'maarten-analyses',
    'immune_editing', 'continuous_IE_detection_init.R'))
# coef_df <- broom.mixed::tidy(me_mod, effects = c('fixed'), conf.int = T)
extract_tumor_type_estimates(me_mod)
ranef(me_mod)
```

```{r, warning=FALSE}
# shinyMer(me_mod, simData = f_setting_dtf[1:10, ])
```
  
```{r, warning=FALSE}
  coef_dtf <- suppressWarnings(broom.mixed::tidy(me_mod,
      # conf.method = 'profile',
      # conf.method = 'boot',
      # effects = c('fixed', 'ran_coefs'),
      conf.int = F))
  coef_dtf$term

  pacman::p_load('merTools')
  f_setting_dtf$patient_inclusion_crit
  # levels(f_setting_dtf$VE_threshold)
  # unique(f_setting_dtf$patient_inclusion_crit)
  pick <- f_setting_dtf[
    maartenutils::eps(yr_fractional_change, -.2, .01) &
    maartenutils::eps(norm_scale, .3,
      .001)][order(-n_patients)][2] %>%
    # .[, c('analysis_idx', grp_vars), with = F]
    { . }
  # pick$percentile_rank <- '1'
  pick$LOH_HLA <- 'strict_LOHHLA'
  pick$LOH_HLA <- 'LOHHLA'
  pick$LOH_HLA <- 'no_LOHHLA'
  # pick$VE_threshold <- '5'
  # pick$patient_inclusion_crit <- 'FDR10'
  # pick$patient_inclusion_crit <- 'FDR1'
  f_setting_dtf$prediction
  predictions <- merTools::predictInterval(me_mod)
  t_dat <- setDT(cbind(f_setting_dtf, predictions))
  t_dat[, 'residual' := yr_fractional_change - fit]

  summary(me_mod)

  coef_dtf <- suppressWarnings(,
      # conf.method = 'profile',
      # effects = c('fixed', 'ran_coefs'),
      conf.int = T))

  print(timing)
  summary(me_mod)
  class(me_mod)
  lme4:::predict.merMod
  (me_mod)
  M <- as.matrix(vcov(me_mod))
  heatmap(M)
  fixef(me_mod)
  ranef(me_mod)
  # lmerTest::ranova(me_mod)


  me_mod <- system.time(lme4::lmer(
    formula = c_formula,
    data = f_setting_dtf, 
    REML = T,
    control = lme4::lmerControl(
      optimizer = 'nloptwrap',
      optCtrl = list(
        maxeval = 10,
        xtol_abs = 1e-3,
        xtol_rel = 1e-1
      )
    ),
    weights = 1 / (f_setting_dtf$norm_scale + 1e-4)
  ))

} else {
  me_mod <- readRDS(fn)
}
REs <- brms::ranef(me_mod)
FEs <- brms::fixef(me_mod)
library(broom.mixed)
pacman::p_load(broom.mixed)

tidy(me_mod)
broom.mixed:::tidy.lme
tidy.mixed
print(tidy(me_mod,
    effects = c('fixed', 'ran_coefs'),
    conf.int = T), n = 5)
broom::glance.lmer(me_mod)
```

```{r, warning=FALSE}
source(file.path('~/antigenic_space', 'maarten-analyses',
    'immune_editing', 'continuous_IE_detection_init.R'))
# ranef(me_mod)[[1]] %>% select(`VE_threshold5`)
# ranef(me_mod)[[1]] %>% select(`VE_threshold1`)
# ranef(me_mod)[[1]] %>% select(`VE_thresholdnone`)
# ranef(me_mod)[[1]] %>% pull(VE_threshold5)
# ranef(me_mod)[[1]] %>% apply(2, median)

random_effects_agg <- ranef(me_mod)[[1]] %>%
  {
    tibble(
      'coef' = colnames(.),
      'q05' = apply(., 2, quantile, .05, na.rm = T),
      'q50' = apply(., 2, median),
      'q95' = apply(., 2, quantile, .95, na.rm = T)
    )
  }

coef_groups <- substr(random_effects_agg$coef, 1, 5)
tapply(random_effects_agg$coef, coef_groups, extract_levels,
  simplify = F) %>% unname %>% unlist(recursive = F)
```

```{r, load_lm_model, cache=T, warning=FALSE}
mod_fn <- file.path(rds_dir, 'rlm_NAYR_loss_complete_lm.rds')
# file.remove(mod_fn)
# back_up(mod_fn)
# rm('mod')
if (!file.exists(mod_fn) && !exists('lm_mod')) {
  lm_mod <- lm(yr_fractional_change ~ (focus_allele + tumor_type +
      expression_threshold + sts_filtering +
      VE_threshold + percentile_rank + overlap_var +
      patient_inclusion_crit + LOH_HLA + analysis_name)^2,
    data = f_setting_dtf, weights = 1/(norm_scale))
  saveRDS(lm_mod, mod_fn)
} else {
  lm_mod <- readRDS(mod_fn)
}
coef_df <- broom::tidy(lm_mod) %>%
  dplyr::rename(std_error = std.error, p = p.value)
table(cut(coef_df$p, breaks = c(0, 1e-3, 5e-2, 1e-1, 1)))
hist(-log10(coef_df$p), breaks = 1000)
```

High residuals tend to be produced by relatively high scale models

```{r, eval = F, warning=FALSE}
# idx = 4024
# lm_mod$model[idx, ]
# predict(lm_mod, lm_mod$model[idx, ])
# hist(residuals(lm_mod), breaks = 1000)

print_plot({
  tibble(
    resid = residuals(lm_mod),
    scale = f_setting_dtf$norm_scale) %>%
    ggplot(aes(x = scale, y = resid)) + geom_hex(bins = 400) +
    theme(
      legend.position = c(.05, .95),
      legend.justification = c(0, 1)
    ) +
    xlab('MAD of normalized residuals') +
    ylab('Meta-model prediction residual')
}, fn = file.path(img_loc, 'residuals_vs_scale.png'), 
  w = 8.7, h = 8)

print_plot(autoplot(lm_mod), fn = 'residuals.png', 
  w = 17.4, h = 15)
```

```{r, warning=FALSE}
source(file.path('~/antigenic_space', 'maarten-analyses', 
    'immune_editing', 'continuous_IE_detection_init.R'))
t_dat <- extract_tumor_type_estimates(lm_mod)
t_dat %>% 
  arrange(estimate_corr) %>%
  mutate(term = factor(term, levels = unique(term))) %>%
  forest_plot('term')
```

